from __future__ import annotations


VERIFIED_DATE = "August 4, 2026"

BOUNDARY_NOTE = (
    "Strict Potrero Hill core used for this search: roughly 16th Street on the north, "
    "US-101 and Potrero Avenue on the west, Cesar Chavez Street on the south, and the "
    "I-280, Pennsylvania, and Texas Street edge on the east. Dogpatch-only addresses "
    "east of that edge are excluded. San Francisco treats neighborhood lines as general, "
    "so border addresses are labeled."
)


POTRERO_LISTINGS = [
    {
        "rank": 1,
        "title": "$1,500 bedroom in shared Potrero house",
        "address": "Potrero Hill / Mission edge; exact address withheld",
        "housing_type": "Private room in house",
        "beds_baths": "1 private bedroom; shared shower room",
        "total_rent": 1500,
        "personal_cost": 1500,
        "cost_basis": "Advertised room rent",
        "availability": "September 1, 2026",
        "furnished": "Unknown; ask lister",
        "household": "Existing household size is not stated. Confirm the home stays at four people or fewer.",
        "source": "Craigslist",
        "url": "https://www.craigslist.org/view/d/san-francisco-1500-month-bedroom/nTtxoQUbfE67uv7WZhTzQz",
        "verified": VERIFIED_DATE,
        "fit": "Best value",
        "why": "Lowest credible core-area room price, with a September move-in and easy access to both Potrero and the Mission.",
        "uncertainty": "Exact address, furnishings, bathroom count, and current household size are not disclosed.",
        "shortlist": True,
    },
    {
        "rank": 2,
        "title": "Furnished room with shared bath",
        "address": "Potrero Hill; exact address withheld",
        "housing_type": "Private room in Victorian apartment",
        "beds_baths": "Room in 3BR / 2BA",
        "total_rent": 1650,
        "personal_cost": 1650,
        "cost_basis": "$1,500 rent + $150 fixed utilities",
        "availability": "September 1, 2026",
        "furnished": "Furnished: queen bed, desk, dresser",
        "household": "Single occupant only; no couples. Listing implies a three-person apartment, but confirm.",
        "source": "Craigslist",
        "url": "https://www.craigslist.org/view/d/san-francisco-furnished-room-with/5gKczTPtQNjpbw1Ng4Xaei",
        "verified": VERIFIED_DATE,
        "fit": "Excellent",
        "why": "Utilities and furniture are already priced in, and the three-bedroom setup should remain below the four-person cap.",
        "uncertainty": "Exact address and identities of the other occupants are not public.",
        "shortlist": True,
    },
    {
        "rank": 3,
        "title": "Beautiful Room in a Happy House",
        "address": "Potrero Hill near Zuckerberg SF General; exact address shared by host",
        "housing_type": "Private room in shared apartment",
        "beds_baths": "Room in 2BR / 1 shared BA",
        "total_rent": 1850,
        "personal_cost": 1850,
        "cost_basis": "Room rent; utilities included",
        "availability": "November 1, 2026",
        "furnished": "Furnished",
        "household": "Shared with the owner and a poodle; two people total after move-in.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/636708_1",
        "verified": VERIFIED_DATE,
        "fit": "Great value",
        "why": "A true two-person household, utilities included, and well inside the preferred range.",
        "uncertainty": "Host states they smoke tobacco, while the page also says smoking is not allowed. Calendar was last updated May 10; reconfirm before applying.",
        "shortlist": True,
    },
    {
        "rank": 4,
        "title": "Peaceful flat at the tip top of Potrero Hill",
        "address": "Top of Potrero Hill; exact address shared by host",
        "housing_type": "Private room in shared apartment",
        "beds_baths": "Room in 3BR / 2BA; 1 shared BA listed",
        "total_rent": 1955,
        "personal_cost": 1955,
        "cost_basis": "Room rent; utilities included",
        "availability": "October 31, 2026",
        "furnished": "Furnished",
        "household": "Large shared flat with dogs. Number of current human occupants is not stated; confirm four or fewer total.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/976110_1",
        "verified": VERIFIED_DATE,
        "fit": "Great value",
        "why": "A quiet hilltop room with utilities included and an updated July availability calendar.",
        "uncertainty": "Exact address and present household count are withheld by the platform.",
        "shortlist": True,
    },
    {
        "rank": 5,
        "title": "Three-bedroom furnished townhouse at 696 De Haro",
        "address": "696 De Haro St #1611, San Francisco, CA 94107",
        "housing_type": "Entire furnished townhouse",
        "beds_baths": "3BR / 2BA",
        "total_rent": 6580,
        "personal_cost": 2193,
        "cost_basis": "Equal three-person split",
        "availability": "Active; move-in and term affect price",
        "furnished": "Furnished",
        "household": "Plan assumes three roommates total, within the four-person maximum.",
        "source": "Zumper / Blueground",
        "url": "https://www.zumper.com/apartments-for-rent/san-francisco-ca/potrero-hill",
        "verified": VERIFIED_DATE,
        "fit": "Excellent split",
        "why": "One of the lowest verified three-bedroom shares, with an exact core address and turnkey furnishings.",
        "uncertainty": "Zumper shows an advertised starting rate. Blueground pricing changes with dates and lease length; request the exact quote.",
        "shortlist": True,
    },
    {
        "rank": 6,
        "title": "Two-bedroom flat with Bay views and private deck",
        "address": "Potrero Hill; exact address shared by host",
        "housing_type": "Entire furnished apartment",
        "beds_baths": "2BR / 1BA",
        "total_rent": 4295,
        "personal_cost": 2148,
        "cost_basis": "Equal two-person split",
        "availability": "August 25, 2026",
        "furnished": "Furnished; utilities included",
        "household": "Plan assumes two roommates total.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/897458_1",
        "verified": VERIFIED_DATE,
        "fit": "Excellent split",
        "why": "The strongest whole-apartment value: a preferred-range share, private deck, and only a one-month minimum.",
        "uncertainty": "Furnished Finder withholds the street address until the host responds.",
        "shortlist": True,
    },
    {
        "rank": 7,
        "title": "Sun-drenched room in central Potrero Hill",
        "address": "Heart of Potrero Hill; exact address withheld",
        "housing_type": "Private room in apartment",
        "beds_baths": "Room in 2BR; bathroom count not stated",
        "total_rent": 2200,
        "personal_cost": 2200,
        "cost_basis": "Advertised room rent",
        "availability": "Listed for August 1, 2026; ask about immediate move-in",
        "furnished": "Unknown; ask lister",
        "household": "One existing roommate, so two people total after move-in.",
        "source": "Listings Project",
        "url": "https://www.listingsproject.com/listings/sun-drenched-spacious-apartment-in-the-heart-of-potrero-hill",
        "verified": VERIFIED_DATE,
        "fit": "Excellent",
        "why": "A two-person household, central neighborhood claim, abundant light, and a preferred-range room price.",
        "uncertainty": "Exact address, bathroom count, furnishings, and revised move-in timing are not public.",
        "shortlist": True,
    },
    {
        "rank": 8,
        "title": "Large furnished primary bedroom in Edwardian home",
        "address": "Potrero Hill; exact address withheld",
        "housing_type": "Private primary room in house",
        "beds_baths": "Room in 2BR / 2BA",
        "total_rent": 2250,
        "personal_cost": 2250,
        "cost_basis": "Advertised room rent",
        "availability": "August through November 2026",
        "furnished": "Furnished: king bed and workspace",
        "household": "Shared with owner; owner's partner sometimes visits. Usually two people, occasionally three.",
        "source": "Craigslist",
        "url": "https://www.craigslist.org/view/d/san-francisco-large-furnished-primary/nowsC6fQnN4HpDUDm6RXTi",
        "verified": VERIFIED_DATE,
        "fit": "Excellent",
        "why": "Mostly private bathroom access, a small household, and a furnished short-term fit within budget.",
        "uncertainty": "Exact address is withheld and the bathroom is shared when the owner's partner visits.",
        "shortlist": True,
    },
    {
        "rank": 9,
        "title": "Private room in Potrero condo near Whole Foods",
        "address": "17th St at Kansas / Rhode Island St, San Francisco, CA 94107",
        "housing_type": "Private room in condo",
        "beds_baths": "Room in 2BR / 2BA; private bath",
        "total_rent": 2350,
        "personal_cost": 2350,
        "cost_basis": "Advertised room rent",
        "availability": "Listed for August 1, 2026; confirm immediate opening",
        "furnished": "Furnished status not clearly stated",
        "household": "One existing roommate, so two people total after move-in.",
        "source": "Craigslist",
        "url": "https://www.craigslist.org/view/d/san-francisco-mission-bay-condo-whole/7v8fi1VNBKxSFvjsz9W9nC",
        "verified": VERIFIED_DATE,
        "fit": "Strong",
        "why": "Private en-suite bath, exact cross streets, and a two-person household at the north-slope edge.",
        "uncertainty": "The title says Mission Bay, but the stated Kansas / Rhode Island location is inside the strict Potrero search area. Confirm furnishings and current availability.",
        "shortlist": False,
    },
    {
        "rank": 10,
        "title": "Temporary two-bedroom at 229 Mississippi",
        "address": "229 Mississippi St, San Francisco, CA 94107",
        "housing_type": "Entire apartment",
        "beds_baths": "2BR / 1BA",
        "total_rent": 4750,
        "personal_cost": 2375,
        "cost_basis": "Equal two-person split",
        "availability": "Target September 26, 2026",
        "furnished": "Basic furnished option may be possible",
        "household": "Plan assumes two roommates total.",
        "source": "Craigslist",
        "url": "https://www.craigslist.org/view/d/san-francisco-229-mississippi-street/abTRkJbEitHHTNdcdzpH4L",
        "verified": VERIFIED_DATE,
        "fit": "Strong split",
        "why": "Exact north-slope address, a preferred-range share, and a flexible three-to-six-month lease.",
        "uncertainty": "Move-in depends on the current tenant leaving, cleaning, and completed lease documents.",
        "shortlist": False,
    },
    {
        "rank": 11,
        "title": "Potrero Hill Perch",
        "address": "Potrero Hill; exact address shared by host",
        "housing_type": "Private room in house",
        "beds_baths": "1 private room / 1 private BA",
        "total_rent": 2450,
        "personal_cost": 2450,
        "cost_basis": "Room rent; utilities and biweekly cleaning included",
        "availability": "Available; exact date by inquiry",
        "furnished": "Furnished",
        "household": "Owner lives in the house with a small dog; max occupancy for the room is one.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/967528_1",
        "verified": VERIFIED_DATE,
        "fit": "Conditional",
        "why": "Private bath, utilities, cleaning, and a neighborhood host, all within the preferred range.",
        "uncertainty": "Travel nurses, physicians, and hospital staff only. Calendar was last updated February 23; reconfirm dates.",
        "shortlist": False,
    },
    {
        "rank": 12,
        "title": "Remodeled two-bedroom on 18th Street",
        "address": "1548 18th St, San Francisco, CA 94107",
        "housing_type": "Entire apartment",
        "beds_baths": "2BR / 1BA",
        "total_rent": 5000,
        "personal_cost": 2500,
        "cost_basis": "Equal two-person split",
        "availability": "Available now",
        "furnished": "Unfurnished; not explicitly stated",
        "household": "Plan assumes two roommates total.",
        "source": "HotPads",
        "url": "https://hotpads.com/1548-18th-st-san-francisco-ca-94107-1y2221j/pad",
        "verified": VERIFIED_DATE,
        "fit": "Strong split",
        "why": "Right on the neighborhood's commercial spine, at the top of the preferred per-person range.",
        "uncertainty": "The listing does not explicitly label furnishing status; tenant pays utilities.",
        "shortlist": False,
    },
    {
        "rank": 13,
        "title": "Three-bedroom with office, yoga room, and parking",
        "address": "Potrero Hill; exact address shared by host",
        "housing_type": "Entire furnished apartment",
        "beds_baths": "3BR / 1BA + bonus room",
        "total_rent": 7750,
        "personal_cost": 2583,
        "cost_basis": "Equal three-person split",
        "availability": "August 22, 2026",
        "furnished": "Furnished; utilities included",
        "household": "Plan assumes three roommates total.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/843648_1",
        "verified": VERIFIED_DATE,
        "fit": "Good split",
        "why": "A real third bedroom, separate bonus room, parking, and a share close to the preferred range.",
        "uncertainty": "Calendar was last updated February 18 and the $8,000 deposit exceeds one month's rent. Reconfirm both.",
        "shortlist": False,
    },
    {
        "rank": 14,
        "title": "638 Rhode Island Street, Unit C",
        "address": "638 Rhode Island St Unit C, San Francisco, CA 94107",
        "housing_type": "Entire apartment",
        "beds_baths": "2BR / 1BA, about 550 sq ft",
        "total_rent": 5200,
        "personal_cost": 2600,
        "cost_basis": "Equal two-person split",
        "availability": "Active unit; exact move-in date not stated",
        "furnished": "Unknown; ask property manager",
        "household": "Plan assumes two roommates total.",
        "source": "Zillow",
        "url": "https://www.zillow.com/b/638-rhode-island-st-san-francisco-ca-9NK7Bk/",
        "verified": VERIFIED_DATE,
        "fit": "Good split",
        "why": "Exact north-slope address with a per-person cost only slightly above the preferred band.",
        "uncertainty": "Zillow's building page showed Unit C in current search results, but furnishing and move-in details require manager confirmation.",
        "shortlist": False,
    },
    {
        "rank": 15,
        "title": "Clean and cozy one-bedroom garden cottage",
        "address": "Potrero Hill near Zuckerberg SF General; exact address shared by host",
        "housing_type": "Entire cottage",
        "beds_baths": "1BR / 1 private BA",
        "total_rent": 2700,
        "personal_cost": 2700,
        "cost_basis": "Solo rent; utilities included",
        "availability": "December 20, 2026",
        "furnished": "Furnished",
        "household": "Private cottage for one person.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/563020_1",
        "verified": VERIFIED_DATE,
        "fit": "Good solo option",
        "why": "One of the few credible solo homes under $3,000, with utilities included.",
        "uncertainty": "Six-month minimum and a December move-in. Calendar was last updated April 29; reconfirm.",
        "shortlist": False,
    },
    {
        "rank": 16,
        "title": "Three-bedroom home at 536 Mississippi",
        "address": "536 Mississippi St, San Francisco, CA 94107",
        "housing_type": "Entire single-family house",
        "beds_baths": "3BR / 1BA; third room is a large bonus room",
        "total_rent": 8300,
        "personal_cost": 2767,
        "cost_basis": "Equal three-person split",
        "availability": "Available now; listed for July 20",
        "furnished": "Unfurnished; not explicitly stated",
        "household": "Plan assumes three roommates total.",
        "source": "HotPads",
        "url": "https://hotpads.com/536-mississippi-st-san-francisco-ca-94107-suwj93/pad",
        "verified": VERIFIED_DATE,
        "fit": "Good split",
        "why": "A full house with yard, garage, and exact address while keeping a three-person share below $2,800.",
        "uncertainty": "Zillow marks its copy off-market while HotPads still shows an active contact path. Treat as time-sensitive and confirm before paying anything.",
        "shortlist": False,
    },
    {
        "rank": 17,
        "title": "Large furnished three-bedroom with views and parking",
        "address": "Potrero Hill / Dogpatch edge; exact address shared by host",
        "housing_type": "Entire furnished condo",
        "beds_baths": "3BR / 2BA",
        "total_rent": 8500,
        "personal_cost": 2833,
        "cost_basis": "Equal three-person split",
        "availability": "September 30 to December 19, 2026",
        "furnished": "Furnished; utilities included",
        "household": "Plan assumes three roommates total, even though the listing permits up to six.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/797138_1",
        "verified": VERIFIED_DATE,
        "fit": "Good short-term split",
        "why": "Three genuine bedrooms, two baths, parking, terrace, and a clearly bounded fall availability window.",
        "uncertainty": "Platform hides the address and labels the area Potrero Hill / Dogpatch. Verify that the pin is west of the strict eastern boundary.",
        "shortlist": False,
    },
    {
        "rank": 18,
        "title": "Furnished two-bedroom, two-bath sublet",
        "address": "Potrero Hill; exact address withheld",
        "housing_type": "Entire furnished apartment",
        "beds_baths": "2BR / 2BA",
        "total_rent": 5650,
        "personal_cost": 2825,
        "cost_basis": "Equal two-person split",
        "availability": "August and September 2026 only",
        "furnished": "Furnished",
        "household": "Plan assumes two roommates total.",
        "source": "Craigslist",
        "url": "https://www.craigslist.org/view/d/san-francisco-huge-br-ba-apartment/wBbrJx8LME7DvdSTZnL3PT",
        "verified": VERIFIED_DATE,
        "fit": "Good short-term split",
        "why": "Two bathrooms and turnkey furnishing make the short two-month window easy to use.",
        "uncertainty": "Exact address is withheld; confirm it lies inside the strict boundary before touring.",
        "shortlist": False,
    },
    {
        "rank": 19,
        "title": "Views condo with private deck",
        "address": "Potrero Hill; exact address shared by host",
        "housing_type": "Entire furnished condo",
        "beds_baths": "2BR / 1BA",
        "total_rent": 5800,
        "personal_cost": 2900,
        "cost_basis": "Equal two-person split",
        "availability": "November 3, 2026",
        "furnished": "Furnished; utilities included",
        "household": "Plan assumes two roommates total.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/747721_1",
        "verified": VERIFIED_DATE,
        "fit": "Within hard cap",
        "why": "Current calendar update, two queen bedrooms, private deck, and a flexible one-month minimum.",
        "uncertainty": "Exact address is withheld until inquiry.",
        "shortlist": False,
    },
    {
        "rank": 20,
        "title": "1386 Rhode Island Street",
        "address": "1386 Rhode Island St, San Francisco, CA 94110",
        "housing_type": "Entire furnished apartment",
        "beds_baths": "2BR / 1BA",
        "total_rent": 5850,
        "personal_cost": 2925,
        "cost_basis": "Equal two-person split before possible utility fee",
        "availability": "October 14, 2026",
        "furnished": "Furnished",
        "household": "Plan assumes two roommates total.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/392989_2",
        "verified": VERIFIED_DATE,
        "fit": "Within hard cap",
        "why": "Exact south-slope address, remodel, deck and garden access, and a one-month minimum.",
        "uncertainty": "Page says utilities included but also lists a $300 monthly utilities fee. If charged, your equal share becomes about $3,075.",
        "shortlist": False,
    },
    {
        "rank": 21,
        "title": "Sunny two-bedroom with deck and outdoor office",
        "address": "Potrero Hill; exact address shared by host",
        "housing_type": "Entire furnished apartment",
        "beds_baths": "2BR / 2BA + outdoor office",
        "total_rent": 5900,
        "personal_cost": 2950,
        "cost_basis": "Equal two-person split",
        "availability": "November 19, 2026",
        "furnished": "Furnished; utilities included",
        "household": "Plan assumes two roommates; listing max occupancy is four.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/925857_1",
        "verified": VERIFIED_DATE,
        "fit": "Within hard cap",
        "why": "Two full baths, separate work space, outdoor areas, and max occupancy that matches your limit.",
        "uncertainty": "Calendar was last updated April 26 and exact address is withheld. Reconfirm before relying on the November date.",
        "shortlist": False,
    },
    {
        "rank": 22,
        "title": "Potrero hilltop house with deck, theater, and yard",
        "address": "Potrero Hill; exact address shared by host",
        "housing_type": "Entire furnished house",
        "beds_baths": "3BR / 1BA",
        "total_rent": 8900,
        "personal_cost": 2967,
        "cost_basis": "Equal three-person split",
        "availability": "September 16, 2026",
        "furnished": "Furnished; utilities included",
        "household": "Plan assumes three roommates total.",
        "source": "Furnished Finder",
        "url": "https://www.furnishedfinder.com/property/532972_1",
        "verified": VERIFIED_DATE,
        "fit": "At hard cap",
        "why": "A complete three-bedroom house with strong common space and a short one-month minimum.",
        "uncertainty": "Only one bathroom for three people, exact address withheld, and calendar last updated May 20.",
        "shortlist": False,
    },
    {
        "rank": 23,
        "title": "Furnished three-bedroom on Rhode Island Street",
        "address": "749 Rhode Island St, San Francisco, CA 94107",
        "housing_type": "Entire apartment",
        "beds_baths": "3BR / 2BA",
        "total_rent": 8995,
        "personal_cost": 2998,
        "cost_basis": "Equal three-person split on 12-month rate",
        "availability": "August 31, 2026",
        "furnished": "Unfurnished at quoted rate; furnished short-term costs more",
        "household": "Plan assumes three roommates total.",
        "source": "Zillow",
        "url": "https://www.zillow.com/homedetails/749-Rhode-Island-St-San-Francisco-CA-94107/2070296642_zpid/",
        "verified": VERIFIED_DATE,
        "fit": "At hard cap",
        "why": "Exact central address, three real bedrooms, two baths, and active pricing just under the per-person ceiling.",
        "uncertainty": "Required water/sewer is shown separately on Trulia. Furnished short-term rate is $9,750 plus required cleaning, which exceeds your cap.",
        "shortlist": False,
    },
    {
        "rank": 24,
        "title": "Two-bedroom at 740 Rhode Island, Unit 208",
        "address": "740 Rhode Island St Unit 208, San Francisco, CA 94107",
        "housing_type": "Entire apartment",
        "beds_baths": "2BR / 1BA",
        "total_rent": 5995,
        "personal_cost": 2998,
        "cost_basis": "Equal two-person split",
        "availability": "Available now",
        "furnished": "Unfurnished; not explicitly stated",
        "household": "Plan assumes two roommates total.",
        "source": "Apartments.com",
        "url": "https://www.apartments.com/740-rhode-island-st-san-francisco-ca-unit-208/32bmzbg/",
        "verified": VERIFIED_DATE,
        "fit": "At hard cap",
        "why": "Exact core address, immediate availability, and a direct inquiry path.",
        "uncertainty": "Utilities are extra, so the true share will exceed $3,000. Furnishing status is not stated.",
        "shortlist": False,
    },
    {
        "rank": 25,
        "title": "Two-bedroom at 509 Potrero Avenue, Unit A",
        "address": "509 Potrero Ave #A, San Francisco, CA 94110",
        "housing_type": "Entire apartment",
        "beds_baths": "2BR / 1BA",
        "total_rent": 6000,
        "personal_cost": 3000,
        "cost_basis": "Equal two-person split",
        "availability": "Active in current Zillow search; exact move-in date unknown",
        "furnished": "Unknown; ask lister",
        "household": "Plan assumes two roommates total.",
        "source": "Zillow",
        "url": "https://www.zillow.com/homedetails/509-Potrero-Ave-A-San-Francisco-CA-94110/2085068049_zpid/",
        "verified": VERIFIED_DATE,
        "fit": "At hard cap",
        "why": "A west-boundary address with a two-person share exactly at the maximum.",
        "uncertainty": "Price changed from an earlier $5,500 alert to $6,000. Zillow rate-limited the direct verification, so confirm price and status immediately.",
        "shortlist": False,
    },
    {
        "rank": 26,
        "title": "Private suite and deck in Potrero Victorian",
        "address": "Potrero Hill; exact address withheld",
        "housing_type": "Private suite in shared Victorian",
        "beds_baths": "Room in 2BR / 3BA; private bath",
        "total_rent": 2900,
        "personal_cost": 2900,
        "cost_basis": "Advertised suite rent",
        "availability": "Available now",
        "furnished": "Furnished",
        "household": "One existing roommate, so two people total after move-in.",
        "source": "Craigslist",
        "url": "https://www.craigslist.org/view/d/san-francisco-luxury-private-suite-deck/48o7GSpEUGyMobqtRjJ9UG",
        "verified": VERIFIED_DATE,
        "fit": "Within hard cap",
        "why": "Private bath and deck in a quiet two-person household, but the price is near the ceiling.",
        "uncertainty": "Exact address is withheld and the post has been reposted, so confirm the current URL and never send funds before an in-person or live-video tour.",
        "shortlist": False,
    },
]


POTRERO_CONTACTS = [
    {
        "name": "AMSI furnished condo at The Potrero",
        "address": "451 Kansas St at 17th St",
        "type": "Direct furnished-housing manager",
        "reason": "AMSI publishes a furnished one-bedroom with utilities, parking, and a 30-day minimum on its own site.",
        "status": "Inquiry-only: the direct page does not publish rent or an available date",
        "url": "https://www.amsires.com/furnished-apartments/locations/california/san-francisco/potrero-hill/poks4475",
    },
    {
        "name": "Victoria Mews",
        "address": "605–625 Carolina St",
        "type": "Condo community",
        "reason": "Large two-bedroom layouts, pool, tennis and parking. Recent unit pages now say check back.",
        "status": "No qualifying public opening confirmed on August 4",
        "url": "https://www.apartments.com/605-carolina-st-san-francisco-ca-unit-651/x1xsvjn/",
    },
    {
        "name": "The Potrero",
        "address": "451 Kansas St",
        "type": "Condo building",
        "reason": "North-slope building over Whole Foods with frequent owner-listed two-bedrooms.",
        "status": "Unit 570's direct page changed to off-market",
        "url": "https://www.zillow.com/homedetails/451-Kansas-St-UNIT-570-San-Francisco-CA-94107/89237593_zpid/",
    },
    {
        "name": "88 at the Park",
        "address": "88 Arkansas St",
        "type": "Condo building",
        "reason": "Newer two-bedroom stock beside Jackson Park; individual owners lease units intermittently.",
        "status": "No qualifying public opening confirmed on August 4",
        "url": "https://www.apartments.com/88-at-the-park-san-francisco-ca/vvx9h9d/",
    },
    {
        "name": "Southern Heights four-unit building",
        "address": "107 Southern Heights Ave",
        "type": "Small apartment building",
        "reason": "Top-of-hill two-bedroom layout; small building worth asking about before units syndicate.",
        "status": "Page says check back soon",
        "url": "https://www.apartments.com/107-southern-heights-ave-san-francisco-ca-unit-2/ztp7ydw/",
    },
    {
        "name": "Golden Gate Properties",
        "address": "1143 Rhode Island St and Potrero portfolio",
        "type": "Property manager",
        "reason": "Previously managed a rent-controlled two-bedroom with garage and yard on the south slope.",
        "status": "1143 Rhode Island page says check back soon",
        "url": "https://www.apartments.com/1143-rhode-island-st-san-francisco-ca/5fq8kln/",
    },
    {
        "name": "655 Kansas Street",
        "address": "655 Kansas St",
        "type": "Condo building",
        "reason": "Two-bedroom units with pool and skyline views; owner-managed openings can be brief.",
        "status": "Unit 304 page says check back soon",
        "url": "https://www.apartments.com/655-kansas-st-san-francisco-ca-unit-304/4pr1f3j/",
    },
    {
        "name": "328B Connecticut Street",
        "address": "328B Connecticut St",
        "type": "Owner-managed condo",
        "reason": "Well-located two-bedroom with yard, laundry and a responsive local owner.",
        "status": "Taken off market July 18, 2026",
        "url": "https://hotpads.com/328b-connecticut-st-san-francisco-ca-94107-1xkrfbq/328b/pad",
    },
    {
        "name": "AndreaRentals",
        "address": "1029 Rhode Island St and Bay Area portfolio",
        "type": "Rental concierge / property manager",
        "reason": "Handles furnished, temporary Potrero homes that fit roommate test-runs of the neighborhood.",
        "status": "1029 Rhode Island was removed July 27, 2026",
        "url": "https://www.zillow.com/homedetails/1029-Rhode-Island-St-San-Francisco-CA-94107/15151513_zpid/",
    },
]


OFFICIAL_SITE_AUDIT = [
    {
        "name": "The Grid Potrero Hill",
        "address": "1468 25th St",
        "type": "Official building site",
        "inventory": "2 current 2BR / 2BA units at $6,114 total; available now and August 31",
        "result": "$3,057/person on a two-way split — the closest direct-site near miss, $57 over the hard cap.",
        "status": "Near miss",
        "tone": "near",
        "url": "https://thegridpotrerohill.com/floorplans/",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "Potrero 1010",
        "address": "1010 16th St",
        "type": "Official Equity Residential site",
        "inventory": "16 current units: 13 one-bedrooms and 3 two-bedrooms; 2BR starts at $6,215",
        "result": "$3,108/person at the published shared rate — $108 over the hard cap.",
        "status": "Near miss",
        "tone": "near",
        "url": "https://www.equityapartments.com/san-francisco/potrero-hill/potrero-1010-apartments",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "Alta Potrero",
        "address": "1301 16th St",
        "type": "Official building site / Greystar",
        "inventory": "5 current units: 3 one-bedrooms and 2 two-bedrooms; cheapest 2BR is $7,269.06",
        "result": "$3,634.53/person on a two-way split — $634.53 over the hard cap.",
        "status": "Over cap",
        "tone": "over",
        "url": "https://altapotrero.com/floorplans/",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "Mason on Mariposa",
        "address": "1601 Mariposa St",
        "type": "Official Related Rentals site",
        "inventory": "4 current units: studios and one-bedrooms from $4,000 to $5,350",
        "result": "No current two- or three-bedroom to split; the cheapest solo unit is $1,000 over the hard cap.",
        "status": "Over cap",
        "tone": "over",
        "url": "https://www.relatedrentals.com/apartment-rentals/san-francisco/potrero-hill/mason-mariposa",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "The Landing",
        "address": "1395 22nd St",
        "type": "Official building site; east-border address",
        "inventory": "6 current units: 3 one-bedrooms and 3 two-bedrooms; cheapest 2BR is $7,921",
        "result": "$3,960.50/person on a two-way split. The site brands the building as Dogpatch, so it remains a border check, not a core result.",
        "status": "Border / over cap",
        "tone": "over",
        "url": "https://www.thelandingsf.com/availability/",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "EVE Community Village",
        "address": "1108 Connecticut St",
        "type": "Official BRIDGE Housing site",
        "inventory": "Official page says no availability; affordable-unit waiting list is closed",
        "result": "Excluded from active results because neither an available unit nor an open waitlist can be pursued today.",
        "status": "No availability",
        "tone": "none",
        "url": "https://www.evecommunityvillage.com/",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "AMSI",
        "address": "451 Kansas St",
        "type": "Direct furnished-housing manager",
        "inventory": "Furnished 1BR / 1BA inquiry page with utilities, parking, and a 30-day minimum",
        "result": "Promising direct lead, but rent and move-in date are unpublished, so it is in the contact list rather than counted active.",
        "status": "Inquiry only",
        "tone": "unknown",
        "url": "https://www.amsires.com/furnished-apartments/locations/california/san-francisco/potrero-hill/poks4475",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "ReLISTO",
        "address": "San Francisco inventory",
        "type": "Independent property manager",
        "inventory": "6 unfurnished and 1 furnished current listings checked",
        "result": "No current Potrero Hill address in either direct inventory.",
        "status": "No Potrero match",
        "tone": "none",
        "url": "https://www.relisto.com/search/unfurnished/",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "J.Wavro Associates",
        "address": "San Francisco inventory",
        "type": "Independent leasing brokerage",
        "inventory": "10 current San Francisco listings checked",
        "result": "No current Potrero Hill listing; older Potrero pages now say no longer available.",
        "status": "No Potrero match",
        "tone": "none",
        "url": "https://jwavro.com/rental_list.php?hood=San%20Francisco",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "SF City Rents",
        "address": "Mission / Potrero / Dogpatch inventory",
        "type": "Independent leasing company",
        "inventory": "Direct neighborhood inventory returns “No results found”",
        "result": "No current Potrero opening; historical Potrero pages are explicitly marked rented.",
        "status": "No availability",
        "tone": "none",
        "url": "https://www.sfcityrents.com/mission-potrero",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "Gordon Property Management",
        "address": "San Francisco inventory",
        "type": "Independent property manager",
        "inventory": "4 current direct listings checked",
        "result": "No current Potrero Hill address in the manager's live AppFolio inventory.",
        "status": "No Potrero match",
        "tone": "none",
        "url": "https://gordon.appfolio.com/listings",
        "verified": VERIFIED_DATE,
    },
    {
        "name": "Gaetani Real Estate",
        "address": "San Francisco and San Mateo inventory",
        "type": "Independent property manager",
        "inventory": "12 current direct listings checked",
        "result": "No current Potrero Hill address in the manager's vacancy inventory.",
        "status": "No Potrero match",
        "tone": "none",
        "url": "https://www.gaetanirealestate.com/vacancies",
        "verified": VERIFIED_DATE,
    },
]


SOURCE_COVERAGE = [
    {
        "source": "Zillow, HotPads, and Trulia",
        "result": "Address-level search completed; duplicates merged across the Zillow network and removed pages excluded.",
    },
    {
        "source": "Apartments.com and building pages",
        "result": "Syndicated address pages checked individually; one active fit retained and check-back pages moved to contacts. Official leasing sites are audited separately below.",
    },
    {
        "source": "Craigslist",
        "result": "Apartments, rooms, and sublets searched separately; suspicious $975 and vague $2,500 posts excluded.",
    },
    {
        "source": "Facebook Marketplace and housing groups",
        "result": "Checked in the signed-in browser. No qualifying active core listing: one Potrero room is pending, one group household would exceed four adults, and other results were outside Potrero.",
    },
    {
        "source": "Furnished Finder",
        "result": "Property pages opened individually; current inquiry pages retained with calendar-age warnings where needed.",
    },
    {
        "source": "Zumper, Listings Project, Realtor.com",
        "result": "Distinct active options retained; syndicated duplicates and out-of-boundary results removed.",
    },
    {
        "source": "Roomies, SpareRoom, PadMapper, property managers",
        "result": "Room-rental sources produced no additional distinct, verifiable core option under the share cap; promising addresses remain in direct outreach.",
    },
    {
        "source": "Independent building and manager websites",
        "result": "Twelve direct inventories audited, including JavaScript leasing widgets. No additional active option met the $3,000 personal cap; The Grid was closest at $3,057 per person.",
    },
]


def shortlist() -> list[dict[str, object]]:
    return [listing for listing in POTRERO_LISTINGS if listing["shortlist"]]


def preferred_count() -> int:
    return sum(1000 <= int(listing["personal_cost"]) <= 2500 for listing in POTRERO_LISTINGS)
